name: CI

on:
  push:
    branches: [ setup-task, main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
          
      - name: Check Python version
        run: python --version
          
      - name: Run tests with coverage
        run: |
          pytest --cov=src tests/
          
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          
      - name: Check for large files
        run: |
          find . -type f -size +5M | grep -v "\.git" | wc -l | xargs test 0 -eq